### ISSUE TITLE
[BUG] Multiple discounts doesn't work with cartCreate()

### ISSUE THREAD

**Issue by denniscessan** [Shopify/hydrogen-ui#36]
**Describe the bug**
When adding multiple discounts to a cart with cartCreate() from useCart() it only adds the first discount in the array provided.

**To Reproduce**
1. Create a cart using cartCreate()
`cartCreate({
    discountCodes: ['discount_1', 'discount_2', 'discount_3'],
    lines: line_items
})`

2. Go to checkout with that cart and see that only 'discount_1' is added.

**Expected behaviour**
It should add all discounts provided in the array of discounts.

**Additional context**
Since Shopify now supports multiple discounts it should be supported by Hydrogen stores as well.

- Hydrogen version: ^1.2.0
- Node version: v18.6.0

**Comment by frehner** [comment]
I'll do the work of verifying that it's an API issue; if I confirm it is, then we'll forward on to the SFAPI team.

**Comment by frehner** [comment]
So, with the mutation:

```gql
mutation cartCreate($input: CartInput!) {
  cartCreate(input: $input) {
    cart {
      id
      discountCodes {
        code
      }
    }
    userErrors {
      field
      message
    }
  }
}
```

and the variables:

```gql
{
  "input": {
    "buyerIdentity": {
      "countryCode": "US",
      "deliveryAddressPreferences": {
        "deliveryAddress": {
          "address1": "",
          "address2": "",
          "city": "",
          "company": "",
          "country": "USA",
          "firstName": "",
          "lastName": "",
          "phone": "",
          "province": "",
          "zip": ""
        }
      },
      "email": "test@test.com"
    },
    "discountCodes": [
      "FREESHIPPING",
			"H20"
    ],
    "lines": [
      
    ],
    "note": ""
  }
}
```

I get the response:

```json
{
  "data": {
    "cartCreate": {
      "cart": {
        "id": "gid://shopify/Cart/4e98cb2b3f134b6710da371f47813d8d",
        "discountCodes": [
          {
            "code": "FREESHIPPING"
          },
          {
            "code": "H20"
          }
        ]
      },
      "userErrors": []
    }
  }
}
```

On the demo store, which appears to me that multiple discounts work on cartCreation. Thoughts?
