### ISSUE TITLE
[BUG] CartProvider not taking languageCode into account

### ISSUE THREAD

**Issue by JaapWeijland** [Shopify/hydrogen-ui#42]
**Describe the bug**
When fetching the cart with Hydrogen builtin components, the cart and its products is fetched in the default language - not in a selected language.

When looking at the source graphql query, only the `countryCode` is taking into account, not the `languageCode`:

https://github.com/Shopify/hydrogen/blob/2aaf9ae7b32d5dc3d01aa1974490b5191f491d4d/packages/hydrogen/src/components/CartProvider/cart-queries.ts#L103

**To Reproduce**
Fetch a cart with a product. It won't take the selected language into account.

**Expected behaviour**
Fetch the cart and its products in a given language.

**Additional context**
Add any other context about the problem here. eg.

- Hydrogen version: 1.3.0
- Node version: 16.15.1
- Device details: MacOS

**Comment by frehner** [comment]
Consolidating into Shopify/hydrogen#622
