### ISSUE TITLE
Next.js/React 18 CartContext error

### ISSUE THREAD

**Issue by beamercola** [Shopify/hydrogen-ui#52]
`TypeError: _virtual_with_selector_mjs__WEBPACK_IMPORTED_MODULE_4__.w.exports.useSyncExternalStoreWithSelector is not a function`

Using react 18.2.0

**Comment by frehner** [comment]
If you install the `next` version I believe this should be fixed. You can test it out by doing 

`npm|yarn|pnpm install @shopify/hydrogen-react@next`

And let me know if that works for you!

**Comment by frehner** [comment]
Released in `2022.10.2`
